r"""Stage 2: apply the futures-generated portfolio positions to each feed's daily
return stream and compare strategy P&L (futures vs CFD vs ETF).

Positions come from scripts/_feed_study_out/positions_test.csv (generated by
_portfolio_extract_positions.py). For each ticker we build the daily return of:
  - FUT_adj   : back-adjusted future (what signals were built on) — vol-compressed
  - FUT_real  : UNADJUSTED future (real futures % returns) — fair execution baseline
  - CFD       : Darwinex index/commodity CFD (ES->SP500, GC->XAUUSD, NQ->QQQ*)
  - ETF       : Darwinex/Norgate ETF (ES->SPY, NQ->QQQ, GC->GLD)
  (*NQ has no Nasdaq index CFD on Darwinex, so its "CFD" == QQQ ETF-CFD.)

Portfolio P&L(feed, t) = sum_ticker position_fraction(ticker, t-1) * r_feed(ticker, t).
We validate the FUT reconstruction against the pipeline's own strategy returns,
then report ann return / vol / Sharpe / tracking-error / daily-corr per feed.
"""
from __future__ import annotations
from pathlib import Path
import importlib.util
import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "_out"

from research.feed_comparison import feed_compare as fc

# feed -> per-ticker daily close series builder
CFD = {"ES": ("SP500", "snap"), "NQ": ("QQQ", "snap"), "GC": ("XAUUSD", "snap")}
ETF = {"ES": ("SPY", "snap"), "NQ": ("QQQ", "snap"), "GC": ("GLD", "snap")}


def close_for(ticker: str, feed: str) -> pd.Series:
    if feed == "FUT_adj":
        return fc.s_ohlc(ticker, "D")
    if feed == "FUT_real":
        return fc.s_ohlc_unadj(ticker)
    sym = (CFD if feed == "CFD" else ETF)[ticker][0]
    return fc.s_mt5_snapshot(sym)


def daily_ret(ticker: str, feed: str) -> pd.Series:
    s = close_for(ticker, feed).astype(float)
    s = s[~s.index.duplicated(keep="last")].sort_index()
    return np.log(s).diff().rename(ticker)


def perf(r: pd.Series) -> dict:
    r = r.dropna()
    mu, sd = r.mean() * 252, r.std() * np.sqrt(252)
    return {"ann_ret": mu, "ann_vol": sd, "sharpe": (mu / sd if sd else np.nan)}


def main() -> None:
    pos = pd.read_csv(OUT / "positions_test.csv")
    pos["ticker"] = pos["ticker"].astype(str).str.replace("Ticker.", "", regex=False)
    pos["date"] = pd.to_datetime(pos["datetime"]).dt.normalize()
    tickers = sorted(pos["ticker"].unique())
    wide = pos.pivot_table(index="date", columns="ticker",
                           values="position_fraction", aggfunc="last").sort_index()
    print(f"positions: {wide.index.min().date()}..{wide.index.max().date()} "
          f"tickers={tickers} rows={len(wide)}")

    feeds = ["FUT_adj", "FUT_real", "CFD", "ETF"]
    pnl = {}
    for feed in feeds:
        rets = pd.concat([daily_ret(t, feed) for t in tickers if t in CFD], axis=1)
        rets = rets.reindex(wide.index).reindex(columns=[t for t in tickers if t in CFD])
        w = wide[[t for t in tickers if t in CFD]].shift(1)  # position set at t-1
        port = (w * rets).sum(axis=1, min_count=1)
        pnl[feed] = port.dropna()

    # align all feeds on common dates
    P = pd.DataFrame(pnl).dropna()
    print(f"common P&L window: {P.index.min().date()}..{P.index.max().date()} n={len(P)}")

    # validate against pipeline's own futures-executed returns if present
    srf = OUT / "strategy_returns_futures.csv"
    if srf.exists():
        ext = pd.read_csv(srf, index_col=0)
        ext.index = pd.to_datetime(ext.index).normalize()
        ext = ext.iloc[:, 0].reindex(P.index)
        c = P["FUT_adj"].corr(ext)
        print(f"  [validation] my FUT_adj reconstruction vs pipeline strategy returns: corr={c:.3f}")

    print("\n-- strategy performance by execution feed (OOS test window) --")
    print(f"  {'feed':<10}{'ann_ret':>10}{'ann_vol':>10}{'sharpe':>9}"
          f"{'TE_vs_FUTreal':>15}{'corr_vs_FUTreal':>16}")
    base = P["FUT_real"]
    for feed in feeds:
        m = perf(P[feed])
        te = (P[feed] - base).std() * np.sqrt(252)
        cc = P[feed].corr(base)
        print(f"  {feed:<10}{m['ann_ret']*100:>9.2f}%{m['ann_vol']*100:>9.2f}%"
              f"{m['sharpe']:>9.2f}{te*100:>14.2f}%{cc:>16.4f}")

    # cumulative equity (log) endpoints
    print("\n-- cumulative log-return over window --")
    for feed in feeds:
        print(f"  {feed:<10}{P[feed].sum()*100:>8.2f}%")

    P.to_csv(OUT / "feed_pnl.csv")
    print(f"\nwrote {OUT/'feed_pnl.csv'}")


if __name__ == "__main__":
    main()
